### ISSUE TITLE
Update FAQ section

### ISSUE THREAD

**Issue by kx-chen** [hackcouver/hackcouver.github.io#12]
![Screen Shot 2019-12-27 at 1 22 15 PM](https://user-images.githubusercontent.com/22359229/71533120-e84b7780-28ab-11ea-8911-934b056497de.png)
FAQ needs to be updated with the FAQ from the old website. The image also needs to either be removed or replaced with something relevant. 

cc @P-lxn

**Comment by kevinlu1248** [comment]
Check my recent push request https://github.com/hackcouver/hackcouver.github.io/compare/new-site?expand=1

**Comment by kx-chen** [comment]
@kevinlu1248 Text looks good, but let's find a different image. 

Also be sure to make a PR next time for things (like this) that might possibly require further discussion so we don't end up pushing code prematurely :)

**Comment by kx-chen** [comment]
Done!
