### ISSUE TITLE
Fix Navbar links

### ISSUE THREAD

**Issue by kx-chen** [hackcouver/hackcouver.github.io#14]
As a viewer of the site, I want to be able to click on the navbar links and have them automatically scroll me down to the appropriate section on the website. 
![Screen Shot 2019-12-27 at 1 28 19 PM](https://user-images.githubusercontent.com/22359229/71533282-c0a8df00-28ac-11ea-8943-4805d86c95e7.png)

**Comment by kevinlu1248** [comment]
You can just use anchor tags. I will get onto that over the weekend.

**Comment by kx-chen** [comment]
Sounds great, thanks!!

**Comment by kx-chen** [comment]
I'll quickly take this up, @kevinlu1248 already done a lot :)
